{% set version = "0.11.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-photobiology
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/photobiology_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/photobiology/photobiology_{{ version }}.tar.gz
  sha256: 18c94728053ca70d8293efe8bbe20b6ca408ef4bf6977fc65f41bf2be8b7a697

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=1.0.2
    - r-lubridate >=1.7.8
    - r-plyr >=1.8.4
    - r-polynom >=1.4_0
    - r-rlang >=0.4.8
    - r-rmarkdown >=2.4
    - r-splus2r >=1.2_2
    - r-stringr >=1.4.0
    - r-tibble >=3.0.4
    - r-tidyr >=1.1.2
    - r-zoo >=1.8_8
  run:
    - r-base
    - r-dplyr >=1.0.2
    - r-lubridate >=1.7.8
    - r-plyr >=1.8.4
    - r-polynom >=1.4_0
    - r-rlang >=0.4.8
    - r-rmarkdown >=2.4
    - r-splus2r >=1.2_2
    - r-stringr >=1.4.0
    - r-tibble >=3.0.4
    - r-tidyr >=1.1.2
    - r-zoo >=1.8_8

test:
  commands:
    - $R -e "library('photobiology')"           # [not win]
    - "\"%R%\" -e \"library('photobiology')\""  # [win]

about:
  home: https://www.r4photobiology.info/, https://bitbucket.org/aphalo/photobiology
  license: GPL-2.0-or-later
  summary: Definitions of classes, methods, operators and functions for use in photobiology and radiation meteorology and climatology. Calculation of effective (weighted) and not-weighted irradiances/doses, fluence rates, transmittance, reflectance, absorptance, absorbance and diverse ratios and other derived quantities
    from spectral data. Local maxima and minima. Conversion between energy- and photon-based units. Wavelength interpolation. Astronomical calculations related solar angles and day length. Colours and vision. This package is part of the 'r4photobiology' suite, Aphalo P. J. (2015) <doi:10.19232/uv4pb.2015.1.14>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: photobiology
# Type: Package
# Title: Photobiological Calculations
# Version: 0.9.26
# Date: 2019-02-11
# Authors@R:  c( person("Pedro J.", "Aphalo", email = "pedro.aphalo@helsinki.fi", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-3385-972X")), person("Titta K.", "Kotilainen", role = "ctb", comment = c(ORCID = "0000-0002-2822-9734")), person("Glenn", "Davis", email = "gdavis@gluonics.com", role = "ctb") )
# Description: Definitions of classes, methods, operators and functions for use in photobiology and radiation meteorology and climatology. Calculation of effective (weighted) and not-weighted irradiances/doses, fluence rates, transmittance, reflectance, absorptance, absorbance and diverse ratios and other derived quantities from spectral data. Local maxima and minima. Conversion between energy- and photon-based units. Wavelength interpolation. Astronomical calculations related solar angles and day length. Colours and vision. This package is part of the 'r4photobiology' suite, Aphalo P. J. (2015) <doi:10.19232/uv4pb.2015.1.14>.
# License: GPL (>= 2)
# Depends: R (>= 3.4.0), tibble (>= 2.0.1)
# Imports: stats, polynom (>= 1.3-9), lubridate (>= 1.7.4), plyr (>= 1.8.4), dplyr (>= 0.7.8), splus2R (>= 1.2-2), zoo (>= 1.8-4), rlang (>= 0.3.1)
# Suggests: knitr (>= 1.21), rmarkdown (>= 1.11), testthat (>= 2.0.1), roxygen2 (>= 6.1.1)
# LazyLoad: yes
# LazyData: yes
# ByteCompile: true
# URL: https://www.r4photobiology.info/, https://bitbucket.org/aphalo/photobiology
# BugReports: https://bitbucket.org/aphalo/photobiology/issues
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-02-12 08:47:24 UTC; aphalo
# Author: Pedro J. Aphalo [aut, cre] (<https://orcid.org/0000-0003-3385-972X>), Titta K. Kotilainen [ctb] (<https://orcid.org/0000-0002-2822-9734>), Glenn Davis [ctb]
# Maintainer: Pedro J. Aphalo <pedro.aphalo@helsinki.fi>
# Repository: CRAN
# Date/Publication: 2019-02-12 10:50:02 UTC
