{% set version = '0.9.24' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-photobiology
  version: {{ version|replace("-", "_") }}

source:
  fn: photobiology_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/photobiology_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/photobiology/photobiology_{{ version }}.tar.gz
  sha256: 52afead8f1abb5ea30d15050ffd6bc60d3784f7ecfab52cdfd45473be95de983

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.7.6
    - r-lubridate >=1.7.4
    - r-plyr >=1.8.4
    - r-polynom >=1.3_9
    - r-rlang >=0.2.2
    - r-splus2r >=1.2_2
    - r-tibble >=1.4.2
    - r-zoo >=1.8_3
  run:
    - r-base
    - r-dplyr >=0.7.6
    - r-lubridate >=1.7.4
    - r-plyr >=1.8.4
    - r-polynom >=1.3_9
    - r-rlang >=0.2.2
    - r-splus2r >=1.2_2
    - r-tibble >=1.4.2
    - r-zoo >=1.8_3

test:
  commands:
    - $R -e "library('photobiology')"           # [not win]
    - "\"%R%\" -e \"library('photobiology')\""  # [win]

about:
  home: https://www.r4photobiology.info/, https://bitbucket.org/aphalo/photobiology
  license: GPL (>= 2)
  summary: Definitions of classes, methods, operators and functions for use in photobiology and
    radiation meteorology and climatology. Calculation of effective (weighted) and not-weighted
    irradiances/doses, fluence rates, transmittance, reflectance, absorptance, absorbance
    and diverse ratios and other derived quantities from spectral data. Local maxima
    and minima. Conversion between energy- and photon-based units. Wavelength interpolation.
    Astronomical calculations related solar angles and day length. Colours and vision.
    This package is part of the 'r4photobiology' suite, Aphalo P. J. (2015) <doi:10.19232/uv4pb.2015.1.14>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
