travis:
  secure:
    BINSTAR_TOKEN: AG6Ke0xHVrpIfYaJ4LYVpR8oskzyzmFCE4aUbew1Jqp4Eh7Ni++kk66bF3Vp4aad8skqYPkmM2JDqit51XtRMCB+VqVt7tHebUDHbnpwh3zMasMMjz0gG4TZ3scDdkvqmtOlyK9eWI0ACK36ynjXIGguHapfJoMcJaFeGW8X7wExVUKNldutp9yP1rMlsqwGMAG6snYnpQtMKBG07qOcHGROZeYSRABf4Vjl78pLav+8pWY8Yt78Knm4XdKxjxHYmE13IcZEjlBANyP9cQKkr6QFK96fmArRm6k9sd/CKh6/lJJXGDTjlm8vMeh2e/zvYQMhyPCbfr0gVqCuHJ/dGRJYR9KC5t0RH6K01WLCUwZCwc3f7IbrDLHKguu1DsFyWtEwUM3jR5XCw5Tm/2SYS3wIjYpCfg/p650r7iEtN22e8hrgYBS+BDBckfYWuJkXWiGbt9DhvzJKKTOdw+aI0k7AP2jx32SDbTxFIA+oJ8GQ98L6fqtxad2qUuaDXT0G0xPjsbYj2qt4Q3jBMSLBPr4QuGHZOguWOGAtC6lxVAxhotiEozsof7mA1j3qYMiPD+j0nJ4WYyJIUgoAYWPkgcm47XhauTi+pGGn3frNZG2iVQzXl7AhSmGpBiRexvHz/2Y4/7VU5bIE7UBNw8sgqMFxnkjgVHYSluDy60TKfPE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
