travis:
  secure:
    BINSTAR_TOKEN: PQG/xr/ie+SRcbOkeGgkM6NXxB+Rd8ewDax/Tsz/ehdbgoK6ov9sFyT/y4rIp7l+VbE9w87eevkJztAdxhqpp2EM5k2W0JXgwrCFsv3VjeVE5G/Ww8hA4wtrzNLitiM9nt+mlx03neoiOvJKoeuk/+v22JsKd33XRl5ZoRrHCTETHtLwwrSq3jPghNB34ugGELi5pHy+yn64JmIQ3GLh601rxpMAlP2JSKrWxvnSRbQ/4Mo+jBbIZG+YhGchzPuM/SxtEcwdnyfbLPlmmG+DLAenmUVCxhj7S20RwkuEVWlmWefbJWqxCGRRJrxwcwCIpS7gxJZ6Swpzlw8zfZd+lPXrwvbqOuR+Znk3YrHxB/MVPzk9KWmqfRbmysRW0cwfSbGg++q3M7l9LbDrKLVJCiBqExWUz9JCijZMl8pFH6Ar/ZojjMGqebcBj31SxrwLIXR5CR7FJ9NDxhzKjXHW7yjk5OTIekJaodU7XgWz7yeO2SrrkHOpi2BHIiIVZMKqeRAztlyvFZqrJHl5JF8X4OU7DVgajqGCRoHzyPtS+yyOye0RUR4EjYU0kccLsHJu4VIRszqjzLdiZ9U0NnAT9NfaeSDktNfzAuJZS0eDuEIFE+Og5tvYYZVM9lRkWOLRsXpUPvkPULmw8MXDqjNDySSsRt5NiBJInnkJERT7a6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
