travis:
  secure:
    BINSTAR_TOKEN: rwZqnkA9INbpZkFUUMJsOu9LCdehWaw2fqmCIcDfi4gu+29rlH2RPhRlRmafolhB9mqKGJa6J0A9EzBxSWS7e7WjZHt8+TtO4sxGypSDA6GQUsDnG4lEuKsNpHD4VdNgd65urJwLkD9fe7d1Prvv3+c1ajS387rpWcwxBFIL3c5GsHERNDDpSg9h7YX4uzzk9MNXRRkc/sMMnoVj4kDAoUZcXRgy6RO8r6iVBvjk+06wIr02BwpQgY4jts6mcFNpXXuc9796WaIQc1nUcCg6cP79aFspLzR4ERxNOsX/kYYLlurgWu3oNYq36CHTF8HmJdAvG8uTIj6OPe6/RewQ5gyBD8cXn0B39TtuSQgmqvcBFwvROJncc1toXfqK20CBJpEhYnk0lrG0RoZFJZEoeqe1iS/WHQHL7tYXAasUrKfPzIUIjXqiYp1IPHwGHjdvz+Lp4S935YuRJZ+/o0QlQgMivPiKlBuydnuGBBjrTp9Ncc1FcpC7MLHSQkydXAqziw07IGcw9cESRntQk4R+ztITA5wZv2snxkO0rE4FmYTeETJy3o5o6e9lLWeQWV/LJE17ZDMqjJnGGec9WMhjG5lNXBVJhwl6IdPb9BdpEzAenRHJkWaKVAdl+Z3PqkxHsfSK5EAw8sLCQiVoukbtNYCrz1uyPnb1VIucHSaHGwc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
