travis:
  secure:
    BINSTAR_TOKEN: TFtbEnuC0IuJIBkMwW4iU+7M7pMAaAs2vo22+1vAaK0BuVL0rdkihFoL4GiDjPDmsiuVZ0ElbNAeRTkT67Ql58zIrqQ+YBM6QAPmrBPeHtbW63HU1vHqgEqDqe7C5VKcxmAcB7G0AF+c+XBMOaBKl49zPUAWOvoeR6SWqamNPOWn8E9X1l5CqiOzef2/P2rpyu3W+S949KOUlBK9VdkIGMQ4yQbiC8VO7VhPIogKiNaBBMDO8V+ed+zCRK7cg+HiypYdjYxsCgxQgxUE1SbsLP932ilCklfRKkpM0EMNojPVApjFS4mMjjReISq4C29SbIUGIAp8WboSjctMzlDpCemG15sQNNixZIsVd84VTcOjQiEHnDbS1zGu5bidLAOrZ96MFXoo/qXsN2BOkKahEwiIJSovvlLU1MMC788P5XnygBLS58M5EblhKWM69+quSj9OxSrS+FXAmRGwnkP/UCw3PppXQuwLkhntRz1xKb3gA8LejbHfCMErp7y4YJx/FTpDH1lB0luYKGCZyBdRouRAXxHpCmtPzfw8C2kbVccwzLET0XGczUOklHYEDSS/oWs5ulDJg+4cJFTt8ORR0byDeDh/E0yQn54UN+fehd1ARbxqSitm/UZZFvtoEKZ7dur9nrpssw2pFucEJXjpaysN/tHgCINZJigexPar3ek=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
